In [1]:
import pandas as pd

/home/tongmeng_xie/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [10]:
# import os
# os.listdir()

temp = pd.read_csv("final_sample3000_ver0_2.csv")
temp.sex_patent = temp.sex_patent.apply(lambda x: 1 if x == 0 else 2)
temp

,patent_id,patent_count,recid,pname_pname_jarowinkler,sname_sname_jarowinkler,county_state_county_state_levenshtein,desc_ori_hisco_text_levenshtein,occ_similarity_HISCO,city/metro_level_l_score,mean,...,sex_census,occhisco,ind95us,county_state_census,metrous,us1880a_city,state_census,patent_year,age_at_inventing,occ_similarity_HISCO_sigmoid
0,US290029A,0.0,25137783.0,1.000000,1.000000,0.958333,1.000000,1.0,0.818182,0.962753,...,1.0,2410.0,898.0,"St Louis City, Missouri",St. Louis,Saint Louis,Missouri,1883,35.0,0.731059
1,US129776A,0.0,19125884.0,0.638889,1.000000,1.000000,1.000000,1.0,1.000000,0.939815,...,2.0,79190.0,448.0,"Suffolk, Massachusetts",Boston,Boston,Massachusetts,1872,35.0,0.731059
2,US265109A,0.0,19319070.0,0.950000,1.000000,1.000000,0.689189,NaN,1.000000,0.927838,...,1.0,39000.0,699.0,"Suffolk, Massachusetts",Boston,Boston,Massachusetts,1882,36.0,NaN
3,US169225A,0.0,39793614.0,1.000000,1.000000,1.000000,1.000000,1.0,0.500000,0.916667,...,1.0,87350.0,346.0,"Lycoming, Pennsylvania",NaN,Williamsport,Pennsylvania,1875,37.0,0.731059
4,US359565A,0.0,16967309.0,1.000000,1.000000,1.000000,1.000000,1.0,0.500000,0.916667,...,1.0,19990.0,899.0,"York, Maine",NaN,NaN,Maine,1887,42.0,0.731059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2234,US307517A,0.0,4165317.0,0.518519,1.000000,0.547619,0.000000,NaN,1.000000,0.613228,...,1.0,58430.0,916.0,"District of Columbia, District of Columbia",Washington,Washington,District of Columbia,1884,28.0,NaN
2235,US224282A,0.0,42179003.0,0.590909,0.850000,1.000000,0.125000,NaN,0.500000,0.613182,...,2.0,99999.0,0.0,"Charleston, South Carolina",NaN,Charleston,South Carolina,1880,30.0,NaN
2236,US347549A,0.0,30459736.0,0.472222,0.855556,1.000000,0.239130,NaN,0.495192,0.612420,...,1.0,45130.0,669.0,"New York, New York",New York-Northeastern NJ,New York,New York,1886,35.0,NaN
2237,US192442A,1.0,3142468.0,0.950000,1.000000,0.611111,0.000000,NaN,0.500000,0.612222,...,1.0,41010.0,626.0,"Pueblo, Colorado",NaN,NaN,Colorado,1877,29.0,NaN
2238,US107010A,1.0,27239912.0,0.472222,0.822222,1.000000,0.179487,NaN,0.583333,0.611453,...,2.0,99999.0,0.0,"Passaic, New Jersey",New York-Northeastern NJ,Paterson,New Jersey,1870,24.0,NaN

In [8]:
temp.columns

Index(['patent_id', 'patent_count', 'recid', 'pname_pname_jarowinkler',
       'sname_sname_jarowinkler', 'county_state_county_state_levenshtein',
       'desc_ori_hisco_text_levenshtein', 'occ_similarity_HISCO',
       'city/metro_level_l_score', 'mean', 'publicationnumber', 'inventor_no',
       'publication.date', 'full_address', 'pname', 'sname', 'sex_patent',
       'occupation', 'industry', 'address', 'street', 'city', 'county_state',
       'state', 'region', 'foreign', 'pname_census', 'sname_census', 'sursim',
       'age', 'sex_census', 'occhisco', 'ind95us', 'county_state_census',
       'metrous', 'us1880a_city', 'state_census', 'patent_year',
       'age_at_inventing', 'occ_similarity_HISCO_sigmoid'],
      dtype='object')

In [14]:
view1 = temp[['patent_id', 'patent_count', 'recid', 'publicationnumber', 'inventor_no',
       'publication.date', 'pname', 'pname_census', 'sname', 'sname_census', 'sex_patent', 'sex_census',
       'street', 'city', 'county_state', 'county_state_census',
       'state', 'state_census', 'region', 'foreign',  'sursim',
       'age',
       'metrous', 'us1880a_city',  'patent_year',
       'age_at_inventing']]
view1['gt'] = False
view1

/tmp/ipykernel_2429/2512866848.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  view1['gt'] = False

,patent_id,patent_count,recid,publicationnumber,inventor_no,publication.date,pname,pname_census,sname,sname_census,...,state_census,region,foreign,sursim,age,metrous,us1880a_city,patent_year,age_at_inventing,gt
0,US290029A,0.0,25137783.0,US290029A,0,11/12/1883,ELLIOTT E,ELLIOTT E,FURNEY,FURNEY,...,Missouri,NaN,False,2.0,32.0,St. Louis,Saint Louis,1883,35.0,False
1,US129776A,0.0,19125884.0,US129776A,0,23/07/1872,BARKER C,MARY E,YOUNG,YOUNG,...,Massachusetts,Middle Atlantic Division,False,1.0,43.0,Boston,Boston,1872,35.0,False
2,US265109A,0.0,19319070.0,US265109A,0,26/09/1882,GEORGE L,GEORGE P,LEWIS,LEWIS,...,Massachusetts,NaN,False,1.0,34.0,Boston,Boston,1882,36.0,False
3,US169225A,0.0,39793614.0,US169225A,0,26/10/1875,ISAAC,ISAAC,BARTON,BARTON,...,Pennsylvania,NaN,False,1.0,42.0,NaN,Williamsport,1875,37.0,False
4,US359565A,0.0,16967309.0,US359565A,0,15/03/1887,FREEMAN,FREEMAN,HANSON,HANSON,...,Maine,NaN,False,1.0,35.0,NaN,NaN,1887,42.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2234,US307517A,0.0,4165317.0,US307517A,0,04/11/1884,EUGENE AV,SAMUEL,APPLEGATE,APPLEGATE,...,District of Columbia,NaN,False,2.0,24.0,Washington,Washington,1884,28.0,False
2235,US224282A,0.0,42179003.0,US224282A,0,10/02/1880,HENRY A DUE,MARY M,JR,JARA,...,South Carolina,NaN,False,1.0,30.0,NaN,Charleston,1880,30.0,False
2236,US347549A,0.0,30459736.0,US347549A,0,17/08/1886,JOHN,JULIUS,ASHCROFT,ASROFF,...,New York,NaN,False,1.0,29.0,New York-Northeastern NJ,New York,1886,35.0,False
2237,US192442A,1.0,3142468.0,US192442A,1,26/06/1877,GEORGE R,GEORGE,RANKIN,RANKIN,...,Colorado,NaN,False,1.0,32.0,NaN,NaN,1877,29.0,False
2238,US107010A,1.0,27239912.0,US107010A,1,06/09/1870,GEORGE,MARY,KRAINK,KRINES,...,New Jersey,NaN,False,1.0,34.0,New York-Northeastern NJ,Paterson,1870,24.0,False

In [15]:
view1.to_csv('view1.csv', index = False)